service: serverless

provider:
  name: aws
  runtime: nodejs22.x
  profile: ricardo-soto-learning
  region: us-west-1
  stage: dev

functions:
  hello:
    handler: src/helloworld.handler
  firstTask:
    handler: src/helloworld.firstTask

plugins:
  - serverless-offline